### ISSUE TITLE
Devlog #2 checklist (also `1.0-alpha.15` release)

### ISSUE THREAD

**Issue by THEGOLDENPRO** [cloudy-org/roseate#39]
- [x] Image drag and drop #23 
- [x] Magnification panel (ui controls) #27 
- [x] Improved font and colours universally.
- [x] First iteration of TOML Configuration. #29 
- [x] Multi-threaded image down-sampling. #33 
- [x] Light mode improvements
- [x] About Roseate panel
- [x] lanczos downscaling too slow https://github.com/cloudy-org/roseate/pull/37
- [x] ``.desktop`` file added
- [x] https://github.com/cloudy-org/roseate/issues/25
- [x] Add `[image.optimizations]` to toml config. #56 
- [x] https://github.com/cloudy-org/roseate/issues/46 (restructure needed)

![Screenshot_20241208_220208](https://github.com/user-attachments/assets/7a1da87f-0508-46bd-ba1c-b286929e5428)

**Comment by r3tr0ananas** [comment]
I think we should release `1.0-alpha.15` because a lot of stuff was added already and keep #25 for the next version.

**Comment by THEGOLDENPRO** [comment]
Egui [0.31.0](https://github.com/emilk/egui/releases/tag/0.31.0) is looking really good for roseate, scene container might be amazing depending how much control it gives me. It may certainly fix #17 for me and potentially save me a lot of time making `ZoomPan` support touch devices 💀 (you may have noticed laptop touchpad and touch screen gestures are none-existent).

Anyways I'll look into all of this when I return to Roseate development and finish #25.
